name: Javascript client CI

on:
  push:
    branches: ["dev"]

permissions:
  contents: write

jobs:
  build-javascript-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - run: npm install
        working-directory: ${{ github.workspace }}

      - name: Install Playwright dependencies
        run: npx playwright install --with-deps
        working-directory: ${{ github.workspace }}


      - name: Fetch current version from npm with tag 'next'
        id: npm_version
        run: |
          version=$(npm show automation_model@next version)
          echo "version=$version" >> $GITHUB_ENV

      - name: Increment version
        id: increment-version
        run: |
          current_version=${{ env.version }}
          IFS='.' read -r -a version_parts <<< "$current_version"
          preid="dev"
          patch_version=$((version_parts[2]+1))
          NEW_VERSION="${version_parts[0]}.${version_parts[1]}.${patch_version}-${preid}"

          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update package.json with new version
        run: |
          jq --arg new_version "${{ env.new_version }}" '.version = $new_version' "${{ github.workspace }}/package.json" > "${{ github.workspace }}/package.json.tmp" && mv "${{ github.workspace }}/package.json.tmp" "${{ github.workspace }}/package.json"

      - name: Update package-lock.json
        run: npm install --package-lock-only
        working-directory: ${{ github.workspace }}

      - run: npm run build
        working-directory: ${{ github.workspace }}

      - name: pull and run HTTPBin Docker container
        run: |
            docker pull kennethreitz/httpbin
            docker run --name httpbin-container -p 3000:80 kennethreitz/httpbin
      - run: npm test
        working-directory: ${{ github.workspace }}

      - name: stop and remove HTTPBin Docker container
        run: |
            docker stop httpbin-container
            docker rm httpbin-container
      - name: publish automation model to npm

        uses: cucumber/action-publish-npm@v1.1.0
        with:
          npm-token: ${{ secrets.NPM_PASSWORD }}
          npm-tag: "next"
          working-directory: ${{ github.workspace }}/build

  dispatch:
    name: Dispatch to Target Repository
    runs-on: ubuntu-latest
    needs: build-javascript-client
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          repository: blinq-io/ai-qa
          event-type: trigger-cucumber-dev
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

