name: Javascript client CI

on:
  push:
    branches: ["dev", "AI-987-change-workflows-to-update-ver"]

permissions:
  contents: write

jobs:
  build-javascript-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm install
        working-directory: ${{ github.workspace }}
      - run: npm version prerelease --no-git-tag-version -preid=dev
        working-directory: ${{ github.workspace }}
      - name: Install Playwright dependencies
        run: npx playwright install
        working-directory: ${{ github.workspace }}

      - run: npm run build
        working-directory: ${{ github.workspace }}
      - run: npm test
        working-directory: ${{ github.workspace }}

      - name: Configure git
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Fetch current version from npm with tag 'next'
        id: npm_version
        run: |
          version=$(npm show automation_model@next version)
          echo "version=$version" >> $GITHUB_ENV

      - name: Commit local changes
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_WORKFLOW }}
        run: |
          git add "${{ github.workspace }}/package.json" "${{ github.workspace }}/package-lock.json"
          git commit -m "Temporary commit to allow merge" || echo "No changes to commit"
          git fetch origin AI-987-change-workflows-to-update-ver
          git merge origin/AI-987-change-workflows-to-update-ver

      - name: Update package.json with current npm version
        run: |
          current_version=${{ env.version }}
          jq --arg current_version "$current_version" '.version = $current_version' "${{ github.workspace }}/package.json" > "${{ github.workspace }}/package.json.tmp" && mv "${{ github.workspace }}/package.json.tmp" "${{ github.workspace }}/package.json"

      - name: Commit updated version
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_WORKFLOW }}
        run: |
          git pull origin AI-987-change-workflows-to-update-ver
          git add "${{ github.workspace }}/package.json" "${{ github.workspace }}/package-lock.json"
          git commit -m "Update version to ${{ env.version }}" || echo "No changes to commit"
          git push origin AI-987-change-workflows-to-update-ver

      - name: Bump version
        run: npm version prepatch --preid=dev
        working-directory: ${{ github.workspace }}

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_WORKFLOW }}
        run: |
          git pull origin AI-987-change-workflows-to-update-ver
          git add "${{ github.workspace }}/package.json" "${{ github.workspace }}/package-lock.json"
          git commit -m "Bump version" 
          git push origin AI-987-change-workflows-to-update-ver

      - name: Publish automation model to npm
        uses: cucumber/action-publish-npm@v1.1.0
        with:
          npm-token: ${{ secrets.NPM_PASSWORD }}
          npm-tag: "next"
          working-directory: ${{ github.workspace }}/build
