# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Javascript client CI

on:
  push:
    branches: ["dev"]

jobs:
  build-javascript-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm install
        working-directory: ${{ github.workspace }}
      - run: npm version prerelease --no-git-tag-version -preid=dev
        working-directory: ${{ github.workspace }}
      - name: Install Playwright dependencies
        run: npx playwright install
        working-directory: ${{ github.workspace }}
      - run: npm run build
        working-directory: ${{ github.workspace }}
      - run: npm test
        working-directory: ${{ github.workspace }}
      - run: npm run version-bump
        working-directory: ${{ github.workspace }}
      - name: publish automation model to npm
        uses: cucumber/action-publish-npm@v1.1.0
        with:
          npm-token: ${{ secrets.NPM_PASSWORD }}
          npm-tag: "next"
          working-directory: ${{ github.workspace }}/build
