name: Javascript client CI

on:
  push:
    branches: ["dev"]

jobs:
  build-javascript-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - run: npm install
        working-directory: ${{ github.workspace }}

      - run: npm version prerelease --no-git-tag-version -preid=dev
        working-directory: ${{ github.workspace }}

      - name: Install Playwright dependencies
        run: npx playwright install
        working-directory: ${{ github.workspace }}

      - run: npm run build
        working-directory: ${{ github.workspace }}

      - run: npm test
        working-directory: ${{ github.workspace }}

      # Ensure changes are committed before version bump
      - name: Commit changes
        run: |
          git config --global user.name "dev-blinq"
          git config --global user.email "guy.arieli@blinq.io"
          git add .
          git commit -m "Auto-commit changes before version bump [skip ci]" || echo "No changes to commit"
        working-directory: ${{ github.workspace }}

      - run: npm run version-bump
        working-directory: ${{ github.workspace }}

      # Push the changes including the version bump using PAT
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          git push origin dev
        working-directory: ${{ github.workspace }}

      - name: publish automation model to npm
        uses: cucumber/action-publish-npm@v1.1.0
        with:
          npm-token: ${{ secrets.NPM_PASSWORD }}
          npm-tag: "next"
          working-directory: ${{ github.workspace }}/build
